# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4364c91a40b41c0e456baeb7b7b8cff"
name = "Just-PopIt"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Scopes needed for Just PopIt pop-up app
scopes = "write_products,read_customers,read_orders,read_themes,write_script_tags,read_content"


[auth]
redirect_urls = [ "https://example.com/api/auth" ]
