# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a0f8d7e4fef49a71af18c8f70f742d37"
name = "Just-PopIt 2.0"
application_url = "https://subliminal-homer-compliably.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://subliminal-homer-compliably.ngrok-free.dev/api/auth",
  "https://subliminal-homer-compliably.ngrok-free.dev/api/auth/callback",
  "https://subliminal-homer-compliably.ngrok-free.dev/auth/callback"
]
