// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/api/triggers/dismissal": {
    params: {};
  };
  "/app/api/triggers/display": {
    params: {};
  };
  "/app/api/templates": {
    params: {};
  };
  "/app/popups": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/api/popups": {
    params: {};
  };
  "/app/popups/new": {
    params: {};
  };
  "/app/api/setup": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/auth/login" | "/auth/*" | "/app" | "/app/api/triggers/dismissal" | "/app/api/triggers/display" | "/app/api/templates" | "/app/popups" | "/app/additional" | "/app/api/popups" | "/app/popups/new" | "/app/api/setup";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/api/triggers/dismissal" | "/app/api/triggers/display" | "/app/api/templates" | "/app/popups" | "/app/additional" | "/app/api/popups" | "/app/popups/new" | "/app/api/setup";
  };
  "routes/app.api.triggers.dismissal.tsx": {
    id: "routes/app.api.triggers.dismissal";
    page: "/app/api/triggers/dismissal";
  };
  "routes/app.api.triggers.display.tsx": {
    id: "routes/app.api.triggers.display";
    page: "/app/api/triggers/display";
  };
  "routes/app.api.templates.tsx": {
    id: "routes/app.api.templates";
    page: "/app/api/templates";
  };
  "routes/app.popups._index.tsx": {
    id: "routes/app.popups._index";
    page: "/app/popups";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.api.popups.tsx": {
    id: "routes/app.api.popups";
    page: "/app/api/popups";
  };
  "routes/app.popups.new.tsx": {
    id: "routes/app.popups.new";
    page: "/app/popups/new";
  };
  "routes/app.api.setup.tsx": {
    id: "routes/app.api.setup";
    page: "/app/api/setup";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.api.triggers.dismissal": typeof import("./app/routes/app.api.triggers.dismissal.tsx");
  "routes/app.api.triggers.display": typeof import("./app/routes/app.api.triggers.display.tsx");
  "routes/app.api.templates": typeof import("./app/routes/app.api.templates.tsx");
  "routes/app.popups._index": typeof import("./app/routes/app.popups._index.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.api.popups": typeof import("./app/routes/app.api.popups.tsx");
  "routes/app.popups.new": typeof import("./app/routes/app.popups.new.tsx");
  "routes/app.api.setup": typeof import("./app/routes/app.api.setup.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};